"""Synthetic, in-memory DuckDB fixtures for research.ml module tests.

These tests are intentionally fast (in-memory DB, tiny synthetic data) so the whole research/ml
suite runs in seconds without requiring ingested real data, while still exercising the real
fpl_quant code paths (backtest.asof_scope, gameweek_deadline, has_double_gameweek, monte_carlo
._team_of_for_fixture) end-to-end.

Data shape: 6 clubs / 18 players across 2 seasons, each GW a full 3-match round-robin card
with realised event_points and ep_outputs Q(x) predictions. Both seasons are backtested to
generate walk-forward split surface.
"""
from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

import pytest

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[3]
SRC_DIR = REPO_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from fpl_quant import db  # noqa: E402

CLUBS = ["A", "B", "C", "D", "E", "F"]
ROUNDS = [
    [("A", "B"), ("C", "D"), ("E", "F")],
    [("B", "C"), ("D", "E"), ("F", "A")],
    [("A", "D"), ("B", "E"), ("C", "F")],
]


def _player_pool():
    """18 players across 6 clubs, 2 GK / 6 DEF / 6 MID / 4 FWD."""
    pos_counts = [("Goalkeeper", 2), ("Defender", 6), ("Midfielder", 6), ("Forward", 4)]
    players = []
    pid = 0
    for pos, n in pos_counts:
        for _ in range(n):
            pid += 1
            players.append((f"p{pid}", pos, CLUBS[pid % 6]))
    return players


@pytest.fixture
def con(tmp_path):
    """In-memory DB with all 17 schema migrations applied, empty."""
    c = db.connect(tmp_path / "ml_test.duckdb")
    yield c
    c.close()


@pytest.fixture
def seeded_db(tmp_path):
    """In-memory DB seeded with 2 seasons of synthetic backtest-ready data.

    Returns the connection, which is closed automatically by DuckDB at test teardown since it
    lives in tmp_path.
    """
    c = db.connect(tmp_path / "ml_seeded.duckdb")
    _seed_two_seasons(c)
    yield c
    c.close()


def _seed_two_seasons(c, seasons=("2024-2025", "2025-2026"), gameweeks=(1, 2, 3)):
    """Seed two seasons of synthetic backtest-ready data per the docstring module comment.

    Simulated Q(x) prediction: team fixtures get ep_outputs rows with ep_total based on an
    arbitrary player-positional expected value, intentionally imperfect so the residual signal
    is nonzero. Realised outcomes (event_points) vary from Q(x) to exercise the model residual.
    Model versions are distinct per season (auto-generated by sequences) so minutes_model_outputs
    -- keyed on (model_version, player_uid) -- can hold one row per player per season.
    """
    now = datetime(2026, 1, 1)

    # Teams + players
    for name in CLUBS:
        c.execute("INSERT INTO dim_team (team_uid, canonical_name) VALUES (?, ?)",
                  [f"team_{name.lower()}", name])
    for pid, pos, club in _player_pool():
        c.execute("INSERT INTO dim_player (player_uid, canonical_name, position) VALUES (?, ?, ?)",
                  [pid, pid, pos])

    backtest_run_id = c.execute(
        "INSERT INTO backtest_runs (warm_up_gameweeks) VALUES (0) RETURNING backtest_run_id"
    ).fetchone()[0]

    # _team_of_for_fixture() (fpl_quant.monte_carlo, reused for team/opponent attribution)
    # resolves rosters via player_alias -> raw_<season>_teams -> team_alias, the same real
    # ingestion-table join the production code uses -- not a parallel resolution path. Seed one
    # raw teams table + fact_raw_ingestion_log + team_alias + player_alias per season, mirroring
    # tests/test_backtest.py's own _seed_season_simulation_league() pattern.
    club_code = {name: str(i + 1) for i, name in enumerate(CLUBS)}
    for season in seasons:
        table = f"raw_{season.replace('-', '_')}_teams"
        c.execute(f'CREATE TABLE "{table}" (code VARCHAR, id VARCHAR, name VARCHAR, short_name VARCHAR)')
        for name in CLUBS:
            code = club_code[name]
            c.execute(f'INSERT INTO "{table}" VALUES (?, ?, ?, ?)', [code, code, name, name[:3]])
            c.execute(
                "INSERT INTO team_alias (alias_name, season, team_uid, alias_source) VALUES (?, ?, ?, 't')",
                [name, season, f"team_{name.lower()}"]
            )
        c.execute(
            "INSERT INTO fact_raw_ingestion_log (raw_table_name, season, source_relpath, "
            "source_file_hash, row_count) VALUES (?, ?, 'teams.csv', ?, ?)",
            [table, season, f"hash_{season}", len(CLUBS)]
        )
        for pid, pos, club in _player_pool():
            c.execute(
                "INSERT INTO player_alias (alias_name, normalized_alias_name, team_code, "
                "season, player_uid) VALUES (?, ?, ?, ?, ?)",
                [pid, pid, club_code[club], season, pid]
            )

    for season in seasons:
        season_year = int(season.split("-")[0])
        # Realised matches with goal data for each gameweek
        match_ids_by_gw = {}
        for gw in gameweeks:
            kickoff = datetime(season_year, 8, gw, 15, 0)
            fixture_pairs = ROUNDS[(gw - 1) % len(ROUNDS)]
            gw_match_ids = []
            for i, (h, a) in enumerate(fixture_pairs):
                mid = f"m_{season}_{gw}_{i}"
                c.execute(
                    "INSERT INTO fact_match (match_id, season, gameweek, kickoff_time, "
                    "home_team_uid, away_team_uid, home_score, away_score, finished, "
                    "competition, _ingested_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, TRUE, 'Premier League', ?)",
                    [mid, season, gw, kickoff, f"team_{h.lower()}", f"team_{a.lower()}", 2, 1, now]
                )
                gw_match_ids.append((mid, h, a))
            match_ids_by_gw[gw] = gw_match_ids

        # Q(x) prediction + realised stats per player per gameweek
        for gw in gameweeks:
            # team_strength_model_versions: a lightweight reference row per season. Not consumed by
            # dataset_builder feature extraction directly, so placeholder values are acceptable here.
            c.execute(
                "INSERT INTO team_strength_model_versions (calibration_asof_date, home_advantage, "
                "xi_params_version, rho_params_version, reference_team_uid) VALUES (?, 0.2, 1, 1, 'team_a')",
                [f"{season[-2:]}-08-01"]
            )
            ts_mv = c.execute("SELECT max(model_version) FROM team_strength_model_versions").fetchone()[0]

            c.execute(
                "INSERT INTO minutes_model_versions (calibration_asof_date, target_season, "
                "decay_params_version, adjustment_params_version, shrinkage_params_version, "
                "fact_multiplier_params_version, lookback_seasons) VALUES (?, ?, 1, 1, 1, 1, '[]')",
                [f"{season[-2:]}-08-01", season]
            )
            mm_mv = c.execute("SELECT max(model_version) FROM minutes_model_versions").fetchone()[0]

            c.execute(
                "INSERT INTO ep_model_versions (calibration_asof_date, target_season, "
                "team_strength_model_version, minutes_model_version, scoring_matrix_params_version, "
                "bps_params_version, bps_tau_params_version) VALUES (?, ?, ?, ?, 1, 1, 1)",
                [f"{season[-2:]}-08-01", season, ts_mv, mm_mv]
            )
            ep_mv = c.execute("SELECT max(model_version) FROM ep_model_versions").fetchone()[0]

            # minutes_model_outputs: one row per player per season (PK is model_version+player_uid).
            for pid, pos, club in _player_pool():
                c.execute(
                    "INSERT INTO minutes_model_outputs (model_version, player_uid, position, "
                    "p_start_historical_final, p_start_historical_position_avg, weight_own, "
                    "logit_adjustment_total, p_start_final, p_used_as_sub_given_not_started, "
                    "p_0min, p_1_59min, p_60plus_min, competitive_matches_last_2_seasons) "
                    "VALUES (?, ?, ?, 0.9, 0.9, 1.0, 0.0, 0.9, 0.0, 0.05, 0.05, 0.9, 20)",
                    [mm_mv, pid, pos]
                )
            deadline = c.execute(
                "SELECT min(kickoff_time) FROM fact_match WHERE season = ? AND gameweek = ? AND competition = 'Premier League'",
                [season, gw]
            ).fetchone()[0]
            # data_asof (the prediction timestamp) must precede the first kickoff -- the prediction
            # is made before any outcome in the gameweek is realized. Set it 1 day before kickoff.
            data_asof = deadline - pd.Timedelta(days=1)
            for pid, pos, club in _player_pool():
                match_id = None
                for mid, h, a in match_ids_by_gw[gw]:
                    if club == h or club == a:
                        match_id = mid
                        break
                if match_id is None:
                    continue

                # Simulated Q(x) prediction: a simplistic but nonzero value based on position
                pos_base = {"Goalkeeper": 2.0, "Defender": 3.0, "Midfielder": 4.0, "Forward": 5.0}.get(pos, 2.0)
                # Add deterministic noise so the model has residuals to learn
                q_pred = pos_base + (gw % 2) * 0.5

                c.execute(
                    "INSERT INTO ep_outputs (model_version, player_uid, fixture_match_id, "
                    "ep_appearance, ep_goals, ep_assists, ep_clean_sheet, ep_goals_conceded, "
                    "ep_defcon, ep_bonus, ep_saves, ep_penalty_save, ep_cards, ep_own_goal, "
                    "ep_total, expected_bps) VALUES (?, ?, ?, 1.0, 0.3, 0.1, 0, 0, 0, 0.2, 0, 0, 0, 0, ?, 20.0)",
                    [ep_mv, pid, match_id, q_pred]
                )

                # Simulated realised stat. Total points are cumulative, event_points is per-GW label.
                realised_pts = max(0, round(q_pred + ((gw - 1) * 0.3 - (gw % 2))))
                # spread actual around prediction so residuals are nonzero
                actual_offset = (pid.count("p")) % 3 - 1
                realised_pts += actual_offset
                c.execute(
                    "INSERT INTO fact_player_season_stats (player_uid, season, gw, now_cost, "
                    "selected_by_percent, chance_of_playing_next_round, status, minutes, "
                    "goals_scored, assists, bps, expected_goals, expected_assists, "
                    "expected_goals_per_90, expected_assists_per_90, "
                    "defensive_contribution_per_90, saves_per_90, total_points, event_points, "
                    "_ingested_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                    [pid, season, gw, 6.0, 5.0, 100.0, "Available", 90, 0, 0, 5, 0.2, 0.1,
                     0.3, 0.2, 0.1, 0.1, realised_pts, realised_pts, now]
                )

                # Prior match stat for player in the gameweek (used by feature_engineering)
                c.execute(
                    "INSERT INTO fact_player_match_stats (player_uid, match_id, season, "
                    "start_min, finish_min, minutes_played, goals, assists, team_goals_conceded, "
                    "tackles, clearances, interceptions, recoveries, blocks, "
                    "_ingested_at) VALUES (?, ?, ?, 0, 90, 90, 0, 0, 1, 1, 2, 1, 3, 1, ?)",
                    [pid, match_id, season, now]
                )

            c.execute(
                "INSERT INTO backtest_gameweek_steps (backtest_run_id, season, gameweek, tier, "
                "data_asof, ep_model_version, mm_model_version, divergence_check_passed) "
                "VALUES (?, ?, ?, 'mature', ?, ?, ?, TRUE)",
                [backtest_run_id, season, gw, data_asof, ep_mv, mm_mv]
            )
